---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Greater Plainstrider")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 3244
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -286.6829
StartingPoint[2] = -2681.438
StartingPoint[3] = 93.0524
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat)