---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highland Strider")
AddNameToAvoidWhiteList("Plains Creeper")
AddNameToAvoidWhiteList("Witherbark Troll")
AddNameToAvoidWhiteList("Boulderfist Ogre")

StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2559
IDs[2] = 2563
IDs[3] = 2552
IDs[4] = 2562
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1298.137
StartingPoint[2] = -2300.937
StartingPoint[3] = 60.05073
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat,true)