---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Skeletal Horror")
AddNameToAvoidWhiteList("Skeletal Mage")
AddNameToAvoidWhiteList("Skeletal Warrior")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 202
IDs[2] = 203
IDs[3] = 48
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10799.58
StartingPoint[2] = -1257.267
StartingPoint[3] = 35.06219
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat)