---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Moonstalker")
AddNameToAvoidWhiteList("Foreststrider")
AddNameToAvoidWhiteList("Rabid Thistle Bear")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2069
IDs[2] = 2322
IDs[3] = 2164
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 6269.504
StartingPoint[2] = 532.4515
StartingPoint[3] = 13.16444
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),1000,StartingFloat)