---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Grizzled Thistle Bear")
AddNameToAvoidWhiteList("Moonstalker Sire")
AddNameToAvoidWhiteList("Giant Foreststrider")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2165
IDs[2] = 2237
IDs[3] = 2323	
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 4719.198
StartingPoint[2] = 247.5807
StartingPoint[3] = 48.50144
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat)