---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highland Razormaw")
AddNameToAvoidWhiteList("Highland Scytheclaw")
AddNameToAvoidWhiteList("Elder Razormaw")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 1018
IDs[2] = 1017
IDs[3] = 1017
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -2737.114
StartingPoint[2] = -1926.81
StartingPoint[3] = 17.65384
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),400,StartingFloat,true)