---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Bluegill Murloc")
AddNameToAvoidWhiteList("Bluegill Puddlejumper")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 1024
IDs[2] = 1025
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -3309.878
StartingPoint[2] = -1122.278
StartingPoint[3] = 7.880129
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat)